/**
 * propertylistTest.java
 *
 * This file was generated by XMLSpy 2010r2 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */

package com.propertylistTest;


public class propertylistTest {
  protected static void example () throws Exception {
  //
  // TODO:
  // Insert your code here...
  //
  // Example code to create and save a structure:
  com.propertylist.propertylist2 doc = com.propertylist.propertylist2.createDocument();
  com.propertylist.trueType root = doc.true2.append();
  // ...
  doc.saveToFile("propertylist1.xml", true);
  //
  // Example code to load and save a structure:
  // com.propertylist.propertylist2 doc =
  // com.propertylist.propertylist2.loadFromFile("propertylist1.xml");
  // com.propertylist.trueType root = doc.true2.first();
  // ...
  // doc.saveToFile("propertylist1.xml", true);

  }

  public static void main (final String args[]) {
    try {
      System.out.println("propertylist Test Application");
      propertylistTest.example();
      System.out.println("OK");
      System.exit(0);
    } catch (final Exception e) {
      e.printStackTrace();
      System.exit(1);
    }
  }
}
